using LibHac;
using LibHac.Common;
using LibHac.Fs;
using LibHac.Fs.Fsa;
using LibHac.FsSystem;
using LibHac.Loader;
using System;
using System.IO;

namespace Ryujinx.HLE.Loaders.Processes.Extensions
{
    public static class NcaExtensions
    {
        public static IFileSystem OpenFileSystem(this Nca nca, NcaSectionType sectionType, IFileSystem fs)
        {
            var ncaFileSystem = new NcaFileSystem(nca, fs);
            return ncaFileSystem;
        }

        public static bool TryGetTitleId(this Nca nca, out ulong titleId)
        {
            titleId = nca.Header.TitleId;
            return titleId != 0;
        }
    }
}
