<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.draganx.ryujinx</ApplicationId>
    <ApplicationVersion>97</ApplicationVersion>
    <ApplicationTitle>DragoNX</ApplicationTitle>
    <ApplicationDisplayVersion>1.0-S20FE-JIT-FIX</ApplicationDisplayVersion>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishTrimmed>false</PublishTrimmed>
    <RunAOTCompilation>false</RunAOTCompilation>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidUseAssemblyStore>false</AndroidUseAssemblyStore>
    <AndroidEnableAssemblyCompression>false</AndroidEnableAssemblyCompression>
  </PropertyGroup>
</Project>
