<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.ryubing.android</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0-MASTER-REAL</ApplicationDisplayVersion>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>false</PublishAot>
    <RunAOTCompilation>false</RunAOTCompilation>
    <AndroidLinkMode>None</AndroidLinkMode>
    <TrimMode>copyused</TrimMode>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <InvariantGlobalization>false</InvariantGlobalization>
    <AndroidEnableAssemblyCompression>false</AndroidEnableAssemblyCompression>
    <AndroidUseAssemblyStore>false</AndroidUseAssemblyStore>
    <IsTrimmable>false</IsTrimmable>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AndroidIncludeDebugSymbols>false</AndroidIncludeDebugSymbols>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidSupportedAbis>arm64-v8a</AndroidSupportedAbis>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ryujinx.Common\Ryujinx.Common.csproj" />
    <ProjectReference Include="..\Ryujinx.Cpu\Ryujinx.Cpu.csproj" />
    <ProjectReference Include="..\Ryujinx.HLE\Ryujinx.HLE.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.GAL\Ryujinx.Graphics.GAL.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.Shader\Ryujinx.Graphics.Shader.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.Vulkan\Ryujinx.Graphics.Vulkan.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.Gpu\Ryujinx.Graphics.Gpu.csproj" />
    <ProjectReference Include="..\ARMeilleure\ARMeilleure.csproj" />
    <ProjectReference Include="..\Ryujinx.Memory\Ryujinx.Memory.csproj" />
    <!-- ESSAS 2 LINHAS CONSERTAM O ERRO DO SEU PRINT -->
    <ProjectReference Include="..\Ryujinx.Ava\Ryujinx.Ava.csproj" />
    <ProjectReference Include="..\Ryujinx.Ava.Common\Ryujinx.Ava.Common.csproj" />
  </ItemGroup>
</Project>
