<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.dragoNX.android</ApplicationId>
    <ApplicationVersion>96</ApplicationVersion>
    <ApplicationDisplayVersion>1.0-S20FE-JIT</ApplicationDisplayVersion>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>
    <!-- Otimizado pro 865 -->
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>false</PublishAot>
    <RunAOTCompilation>false</RunAOTCompilation>
    <AndroidLinkMode>None</AndroidLinkMode>
    <AndroidEnableAssemblyCompression>false</AndroidEnableAssemblyCompression>
    <AndroidUseAssemblyStore>false</AndroidUseAssemblyStore>
    <EmbedAssembliesIntoApk>false</EmbedAssembliesIntoApk>
    <DebugSymbols>false</DebugSymbols>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ryujinx.Common\Ryujinx.Common.csproj" />
    <ProjectReference Include="..\Ryujinx.Cpu\Ryujinx.Cpu.csproj" />
    <ProjectReference Include="..\Ryujinx.HLE\Ryujinx.HLE.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.GAL\Ryujinx.Graphics.GAL.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.Shader\Ryujinx.Graphics.Shader.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.Vulkan\Ryujinx.Graphics.Vulkan.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.Gpu\Ryujinx.Graphics.Gpu.csproj" />
    <ProjectReference Include="..\ARMeilleure\ARMeilleure.csproj" />
    <ProjectReference Include="..\Ryujinx.Memory\Ryujinx.Memory.csproj" />
  </ItemGroup>
</Project>
